# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Jonathan"
include:            ["_pages"]

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /404/
permalink:          /blog/
permalink:          /contact/
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

excerpt_separator: <!--more-->

# Navigation
nav:
  - name:           "Blog"
    href:           "/blog"
  - name:           "Contact"
    href:           "/contact"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Emoji
plugins:
  - jemoji

# Exclude
exclude:
  - README.md
  - docker-compose.yml
  - LICENSE
  - .gitignore
